### PR TITLE
installer: fix missing path to cat

### PR DESCRIPTION
**Pull request by Lillecarl**
Fixes cat not being accessible by installer script

- [x] Allow edits by maintainers

### CODE REVIEW

**Comment by gmodena** [comment]
Hey @Lillecarl ; Thanks for this!

Would you mind sharing some details of the system where this bug popped up? Was it on nixos or another distro?

I did not catch it with integration tests and could not reproduce (nixos).

**Comment by Lillecarl** [comment]
Hi! NixOS-unstable, home-manager master (without nixos module).

Caught by systemd unit failing and home-manager rebuild reporting a failed unit.

See HM systemd.user.startServices = "SD-switch" ;

**Comment by gmodena** [comment]
@Lillecarl ack.  Thanks for sharing!

**Comment by Lillecarl** [comment]
@gmodena any time, you can find my config at lillecarl/nixos if there's any specific you're looking for.

I'd put coreutils and friends in the systemd path rather than messing with all these package paths.

Coreutils "cost" the same in systemd as in a template reference.

**Pull request merged**
