### PR TITLE
fix(dbus): No medium found

### LINKED ISSUE #65: Failed to connect to bus: No medium found
First, I want to say, it installs the flatpaks completely fine?
According to `systemctl status flatpak-managed-install.service --user` it seems to be working:
```log
Apr 08 13:45:27 luminara systemd[2150]: Starting flatpak-managed-install.service...
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115860]: Skippi>
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115865]: Skippi>
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115872]: Skippi>
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115877]: Skippi>
Apr 08 13:45:27 luminara systemd[2150]: Finished flatpak-managed-install.service.
```
`journalctl -f` and `dbus-monitor` shows this and more:
```
systemd1; interface=org.freedesktop.systemd1.Manager; member=JobNew
   uint32 980
   object path "/org/freedesktop/systemd1/job/980"
   string "flatpak-managed-install.service"
```
It seems *it's is* connecting to the bus, the error in the `home manager switch` logs does not seem to matter?
```
Failed to connect to bus: No medium found
```

**Metadata**

```console
[jh-devv@luminara:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/j10523yhkcc34478azkgcl70yzcx6j2j-source`
```

### PR DESCRIPTION
**Pull request by jh-devv**
https://github.com/NixOS/nixpkgs/issues/183629
Should fix #65

### CODE REVIEW

**Comment by jh-devv** [comment]
Noticed that this is the same error I had in my own flake.
Fixed it with this ^-^

**Comment by gmodena** [comment]
hey @jh-devv - thanks for this!

I tried to replicate #65, but I don't see any dbus errors on any of my test envs. I use Gnome, and  `DBUS_SESSION_BUS_ADDRESS` is set:
```
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus,guid=01b38efe8192276454507e05663647ae
```
On my systems, the variable is set by the systemd `dbus.service` unit.  It is then imported by my session manager (GDM).Could you maybe check the output of:
```
systemctl status --user dbus.service
```

I can see how  manually setting `DBUS_SESSION_BUS_ADDRESS` will fix your issue, but  I am not sure if an home-manager's activation script is the right place to declare that variable. 

If anything, I would suggest checking that `DBUS_SESSION_BUS_ADDRESS` is already set before (re)exporting it.

Maybe your session manager, or shell's profile config, could be a better place for exporting the variable?

**Comment by jh-devv** [comment]
> Maybe your session manager, or shell's profile config, could be a better place for exporting the variable?

Maybe, though, *it is* set?

Maybe something weird with Hyprland?

**Comment by gmodena** [comment]
> Maybe, though, it is set?
> Maybe something weird with Hyprland?

mmm... could be? Unfortunately I am not familiar with hyperland.
If you `echo DBUS_SESSION_BUS_ADDRESS` on a fresh install, is the variable set at all ?

If I understand your bug report correctly,  `unix:path=/run/user/$UID/bus` existed in your system after boot, and you did not manually have the create the session.  Is this right?

**Comment by jh-devv** [comment]
Starting Hyprland via an systemd service seemed to fix this?

**Comment by gmodena** [comment]
Closing this MR, since it seems more appropriate to configure (global) dbus state outside of an activation script. If other folks reports similar issues, we can add documentation / pointers to the project.

**Pull request closed without merging**
